### ISSUE TITLE
Steal script, leave author info

### ISSUE THREAD

**Issue by utdrmac** [Phlogi/tezos-snapshots#6]
If you're going to steal someone's code, https://gist.github.com/utdrmac/2125a8514960e163837e86bc934f19b6, then you should leave the original author's information, and leave all original donation addresses. Otherwise, you're just plagiarizing.

**Comment by Phlogi** [comment]
Well, the relevant part of the script is very small compared to what this repo is offering: About 10 relevant lines of the script vs. 500 of the pipeline. This repo is not about offering a very basic script to add peers to a node. 

I understand your point. You do not have license information in your script, not even a copyright notice. I recommend you to add that if it's important to you. 

I updated our version of the script with commit ae09d509275e67208b0b349dbace0109dbf8c2cf nevertheless.
